### ISSUE TITLE
xiso version for xemu on steamdeck

### ISSUE THREAD

**Issue by Tom-Neverwinter** [insignia-live/xblunblock#11]
xiso version for xemu on steamdeck, qwix shows out of range error

extract-xiso seems to not patch properly [tried changing file type to iso with not success]

C-xbox tool patches however doesnt load. [tried changing file type to iso with not success]

qwix make into iso, doesnt boot.  

patch using cxbox tool then create iso in qwix fails

**Comment by thrimbor** [comment]
I cannot deduce what issue you're trying to describe from what you posted.

Why do you even want to run xblunblock in xemu?

**Comment by Tom-Neverwinter** [comment]
to run it on my steamdeck. using my xbox portably is possible but silly.

**Comment by thrimbor** [comment]
I understand you're using xemu on your Steamdeck, I'm asking why you want to run xblunblock in xemu. And what issue you're trying to describe above.

**Comment by Tom-Neverwinter** [comment]
to use my official and legal xbox files I probably need to run xbunlock. its nigh impossible to get a image/backup of the bios on my machine. [rocky 5 tools and other shenanigan's were required to flash\hardmod it after a major recovery]

**Comment by thrimbor** [comment]
Getting a backup of the BIOS on your Xbox is trivial when you already have the Rocky 5 stuff.
xblunblock is only necessary when your BIOS blocks XBL,  which only ever was the case for non-stock systems. Its intended use case is to allow people to bypass XBL blocking temporarily in situations where reflashing is not desired - this does not apply to xemu.

**Comment by Tom-Neverwinter** [comment]
getting a bios isnt possible... the backup tool never worked.... in any version for my system.. flashing alone was a nightmare. I had to hardware rig up a piece to rip it, and I'm not doing that ever again. [bios cannot be obtained with software only] issue page on rocky5 does not exsist anymore... ] **Sharp TSOP sucks**

**Comment by Tom-Neverwinter** [comment]
however if you are saying a sharp tsop is now super easy let me know with a tutorial or video proof... 

https://www.ogxbox.com/forums/index.php?/topic/38-flashing-a-sharp-tsop/#comment-7533

**Comment by thrimbor** [comment]
The flash is memory mapped, dumping it does not differ from one chip manufacturer to another.
Can we get back on topic though?

**Comment by Tom-Neverwinter** [comment]
https://photos.app.goo.gl/EfwcvQLMsrGzjs8L6 based on my photos the bios is a x2 and blocks xbox live, unblock works on my xbox fine as its original hardware however will not work on steamdeck as its emulated.

**Comment by Tom-Neverwinter** [comment]
issue is related to eeprom settings being changed custom settings and having a VPN on.
