### ISSUE TITLE
Not working with iND-BiOS 5004 (iND-BiOS.Beta.Feb-11-05.67.bin)

### ISSUE THREAD

**Issue by KnollControl** [insignia-live/xblunblock#7]
It gets stuck at the point shown in the screenshot.
![xblunblock_ind5004](https://user-images.githubusercontent.com/116759150/198117720-b7e7051a-8fcb-4b9d-92ac-36b07a8df76e.png)

**Comment by Idontknow28** [comment]
It's also not working for me either. I've tried the quick one and the regular one - both freeze.

**Comment by InternalLoss** [comment]
Our apologies for the delay - please try https://github.com/insignia-live/xblunblock/releases/tag/v202301031603 if you have not changed your BIOS.

**Comment by KnollControl** [comment]
This is now working with the latest release, thanks!

**Comment by KnollControl** [comment]
This is now working with the latest release, thanks!
